(() => {
 const params=new URLSearchParams(location.search),overview=params.get('mode')==='overview',view=params.get('mode')==='view';
 const stage=document.querySelector('.stage'),phone=document.querySelector('.phone'),screens=[...document.querySelectorAll('.screen')];
 let savedTrait='',resultTrait='';
 let current=Math.max(0,Math.min(5,Number(params.get('scene'))||0)),generation=0,parents=[0,1],slot=0;
 const files=['charA.jpg','charB.jpg','charC.jpg'];
 function report(manual=false){parent.postMessage({type:overview?'board-height':'flow-state',height:Math.ceil(stage.getBoundingClientRect().height),scene:current,manual,finished:current===5,label:STEPS[current].t},location.origin);}
 function fill(screen){const id=screen.id,chat=document.getElementById(id+'chat');if(chat){chat.innerHTML='';for(const [who,text] of CHATS[id]||[]){const b=document.createElement('div');b.className=who==='day'?'label':'bubble '+who+' show';b.textContent=text;chat.append(b);}}screen.querySelectorAll('.hidden').forEach(e=>e.classList.remove('hidden'));screen.querySelectorAll('[id$="img"],[id$="cap"],[id$="pill"]').forEach(e=>e.style.opacity=1);screen.querySelectorAll('.log>div').forEach(e=>e.classList.add('show'));}
 function fit(){if(overview){const columns=innerWidth>1200?6:innerWidth>650?3:2;stage.style.gridTemplateColumns='repeat('+columns+',minmax(0,1fr))';stage.querySelectorAll('.phone').forEach(p=>p.style.zoom=Math.min(1,(innerWidth-(columns+1)*12)/columns/390));report();}else{const scale=Math.min((innerWidth-16)/390,(innerHeight-16)/844);phone.style.transform='translate(-50%,-50%) scale('+scale+')';}}
 function show(index,manual=false){generation++;current=Math.max(0,Math.min(5,index));screens.forEach((s,i)=>s.classList.toggle('on',i===current));fill(screens[current]);report(manual);fit();}
 function probabilities(){return parents.includes(2)?[45,10,45]:[50,35,15];}
 function drawSources(){document.querySelectorAll('.source-slot').forEach((b,i)=>{b.classList.toggle('pick',slot===i);b.querySelector(':scope>img').src='img/'+files[parents[i]];b.querySelector('b').textContent='원형 '+String.fromCharCode(65+parents[i]);});const odds=document.getElementById('fusion-odds');document.getElementById('compatibility').textContent=parents.includes(2)?'상성 ○':'상성 ◎';if(odds)odds.innerHTML='외형 A '+probabilities()[0]+'% · B '+probabilities()[1]+'% · C '+probabilities()[2]+'%<br>성격·희귀 특징 별도 추첨 · 목업 확률';}
 if(overview){document.body.classList.add('overview');stage.innerHTML='';screens.forEach((screen,i)=>{fill(screen);screen.classList.add('on');const card=document.createElement('article'),p=document.createElement('div'),label=document.createElement('button');p.className='phone';p.append(screen);label.className='scene-caption';label.textContent=String(i+1).padStart(2,'0')+' · '+STEPS[i].t.replace(/^\d+\.\s*/,'');card.append(p,label);card.addEventListener('click',()=>parent.postMessage({type:'board-open',scene:i},location.origin));stage.append(card);});}
 else{document.body.classList.add('embedded');document.querySelector('.side').remove();document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-gacha')){const pick=Math.floor(Math.random()*3);document.querySelector('#s1 .toast').textContent='가챠 결과 · 원형 '+String.fromCharCode(65+pick);parents[0]=pick;parents[1]=(pick+1)%3;drawSources();return;}if(b.dataset.slot!==undefined){slot=Number(b.dataset.slot);drawSources();return;}if(b.dataset.origin!==undefined){const o=Number(b.dataset.origin);if(o!==parents[1-slot])parents[slot]=o;drawSources();return;}if(b.dataset.go){if(b.closest('#s2')&&document.getElementById('fusion-result')){const r=Math.random()*100,p=probabilities(),index=r<p[0]?0:r<p[0]+p[1]?1:2;resultTrait=savedTrait&&Math.random()<.6?savedTrait:(Math.random()<.3?'희귀 인자':'기본 인자');document.getElementById('fusion-result').textContent='외형 '+String.fromCharCode(65+index)+' · '+['다정함','호기심','도도함'][Math.floor(Math.random()*3)]+' · '+resultTrait;}if(b.closest('#s3')&&document.getElementById('fusion-result')){savedTrait=resultTrait;document.getElementById('fusion-odds').innerHTML+='<br>보관 인자 · '+savedTrait+' · 다음 합성 우선 계승 60%';}show(ORDER.indexOf(b.dataset.go),true);}});window.addEventListener('message',e=>{if(e.source!==parent||e.origin!==location.origin||e.data?.type!=='flow-control')return;const c=e.data.command;if(c==='reset')show(0);else if(c==='advance')show(Math.min(5,current+1));else if(c==='jump')show(e.data.scene);else report();});show(current);}
 window.addEventListener('resize',fit);window.addEventListener('load',fit);fit();
})();
