(() => {
 let selected=1,parents=[0,1],saved='',trait='',resultOrigin=0,savedOrigin=0;const files=['charA.jpg','charB.jpg','charC.jpg'];
 const chances=()=>{const base=parents.includes(2)?[45,10,45]:[50,35,15];return saved?base.map((p,i)=>(p+(i===savedOrigin?30:0))/1.3):base;};
 function redraw(){document.querySelectorAll('.source-slot').forEach((b,i)=>{b.classList.toggle('pick',i===selected);b.setAttribute('aria-pressed',String(i===selected));b.querySelector(':scope>img').src='img/'+files[parents[i]];b.querySelector('b').textContent='원형 '+String.fromCharCode(65+parents[i]);});const p=chances().map(n=>Number(n.toFixed(1)));p[2]=Number((100-p[0]-p[1]).toFixed(1));document.getElementById('compatibility').textContent=parents.includes(2)?'상성 ○':'상성 ◎';document.getElementById('fusion-odds').innerHTML='외형 A '+p[0]+'% · B '+p[1]+'% · C '+p[2]+'%<br>성격·희귀 특징 별도 추첨'+(saved?'<br>보관 인자 · '+saved:'');}
 document.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.slot);redraw();});
 document.querySelectorAll('[data-origin]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.origin);if(i!==parents[1-selected])parents[selected]=i;redraw();});
 document.querySelector('[data-gacha]').onclick=()=>{const i=Math.floor(Math.random()*3);document.querySelector('#s1 .toast').textContent='가챠 결과 · 원형 '+String.fromCharCode(65+i);parents=[i,(i+1)%3];redraw();};
 document.querySelector('#s2 [data-go]').addEventListener('click',()=>{const p=chances(),r=Math.random()*100,i=r<p[0]?0:r<p[0]+p[1]?1:2;resultOrigin=i;trait=Math.random()<.3?'희귀 인자':'기본 인자';document.getElementById('fusion-result').textContent='외형 '+String.fromCharCode(65+i)+' · '+['다정함','호기심','도도함'][Math.floor(Math.random()*3)]+' · '+trait;for(const selector of ['#s3 .charbox img','#s4 .charbox img','#s5img img'])document.querySelector(selector).src='img/'+files[i];const chips=document.querySelector('#s3 .chips');chips.textContent='';const badge=document.createElement('span');badge.className='chip on';badge.textContent='외형 '+String.fromCharCode(65+i)+' · '+trait;chips.append(badge);document.querySelector('#s3 .star').textContent=trait==='희귀 인자'?'★ 희귀 특징':'기본 특징';const b=document.querySelector('#s3 .chip.lock');if(b){b.textContent='승계';b.setAttribute('aria-pressed','false');}});
 window.selectCollectedOrigin=i=>{parents=[i,(i+1)%3];redraw();};
 window.keepFusionTrait=keep=>{savedOrigin=resultOrigin;saved=keep?'외형 '+String.fromCharCode(65+resultOrigin)+' · '+trait:'';redraw();};
 redraw();
})();
