const gameId=new URLSearchParams(location.search).get('game')||'g21';
const titles={g21:'계승 공방',g22:'14일의 비밀 동거',g23:'마녀의 비밀 살롱',g24:'왕도 계약 조사대',g25:'7일간 비밀연애'};
const themes={g21:'workshop',g22:'home',g23:'salon',g24:'rpg',g25:'fox'};
const art=g=>`../assets/game-art/${g}.png`;
const initial=()=>({phase:0,affinity:24,materials:18,gold:360,day:3,activity:'요리',trait:'은빛 날개',witch:'리엘',enemy:100,turn:1,log:'기사의 방어로 사수에게 공격 기회를 만드세요.',message:'',album:2,notice:''});
let state=initial();
const root=document.getElementById('game');
const button=(label,action,cls='',extra='')=>`<button type="button" data-action="${action}" class="${cls}" ${extra}>${label}</button>`;
const meter=(value,label)=>`<div class="note-line"><span>${label}</span><span>${value}%</span></div><div class="track"><div class="fill" style="--value:${value}%"></div></div>`;
const progress=()=>`<div class="progress" aria-label="진행 단계 ${state.phase+1}">${[0,1,2].map(n=>`<span class="${n<=state.phase?'done':''}"></span>`).join('')}</div>`;
const portrait=(g,name,role,speech,label)=>`<div class="world"><img class="portrait" src="${art(g)}" alt="${name} 캐릭터 일러스트"><span class="world-label">${label}</span><div class="character"><div class="name">${name}</div><div class="role">${role}</div><p class="speech">“${speech}”</p></div></div>`;
const memory=text=>`<div class="memory"><strong>둘만의 기억</strong>${text}</div>`;
function workshop(){
 let content;
 if(state.phase===0){const filled=[0,1,6,7,12,13,14,19,20,25,26,27,28,29,32];content=`<div><div class="eyebrow">01 / 원형 수집</div><h1>한 줄을 완성해<br>새 원형을 만나세요.</h1><p class="muted">다음 보상 · 마족형 원형 × 1</p></div><div class="panel-box"><div class="box-title"><span>공방 의뢰 03</span><span>목표 4줄 · 현재 3줄</span></div><div class="puzzle" aria-label="블록 퍼즐 보드">${Array.from({length:36},(_,i)=>`<div class="cell ${filled.includes(i)?'filled':''}" style="--cell:${i%3===0?'#b7aae8':i%3===1?'#a7dfd8':'#e6be9a'}"></div>`).join('')}</div><div class="pieces">${button('▣ ▣','collect','piece', 'aria-label="가로 블록을 놓아 줄 완성"')}${button('▣<br>▣','collect','piece', 'aria-label="세로 블록을 놓아 줄 완성"')}</div></div>${button('블록 놓기 · 의뢰 완료','collect','primary wide-button')}`;}
 else if(state.phase===1){content=`<div><div class="eyebrow">02 / 합성 · 승계</div><h1>새 원형에 어떤 특징을<br>이어줄까요?</h1><p class="muted">수집한 원형 본체는 그대로 보관됩니다.</p></div><div class="panel-box"><div class="partners">${['g21','g22'].map((g,i)=>`<button type="button" class="selected" disabled><img src="${art(g)}" alt="합성 원형">${i?'안드로이드형 · 냉정':'마족형 · 호기심'}</button>`).join('')}</div><div class="combine"><div class="orb">◇</div><span>＋</span><div class="orb">✧</div><span>→</span><div class="orb">?</div></div><div class="box-title">승계할 희귀 특징 선택</div><div class="inherit-list">${['은빛 날개','다정한 성격'].map(t=>button(t,'trait:'+t,state.trait===t?'selected':'')).join('')}</div></div>${button('파트너 합성하기 · 재료 12','combine','primary wide-button')}`;}
 else{content=`<div><div class="eyebrow">03 / 나만의 파트너</div><h1>대화가 쌓일수록<br>둘만의 파트너가 됩니다.</h1></div><div class="panel-box"><div class="chips"><span class="chip">마족형</span><span class="chip">호기심</span><span class="chip rare">${state.trait}</span></div><div style="margin-top:16px">${meter(state.affinity,'관계 · 관심')}</div></div>${memory(state.message?'창가에서 별을 함께 보기로 약속했다.':'아직 함께한 사건이 없습니다. 첫 약속을 만들어 보세요.')}<div class="message-choices">${button('오늘 밤, 같이 별을 볼까?','workshop-talk')}</div>${button(state.message?'약속한 장면 · 앨범에 남기기':'첫 대화 시작','workshop-talk','primary wide-button')}`;}
 return portrait('g21','세라','마족형 · 호기심',state.message?'네가 별을 좋아한다고 했지. 오늘은 내가 먼저 기다릴게.':state.phase===2?'내 이름을 불러줄래? 너와 함께할 일을 알고 싶어.':'어떤 모습의 나를 만나고 싶어?','WORKSHOP / 공방')+`<div class="panel">${progress()}${content}<div class="status" role="status">${state.notice}</div></div>`;
}
function home(){
 const next=state.phase===2;
 let content=state.phase===0?`<div><div class="eyebrow">DAY 03 / 아침</div><h1>오늘은 함께<br>무엇을 할까요?</h1><p class="muted">고른 활동이 저녁 대화로 이어집니다.</p></div><div class="panel-box"><div class="box-title">오늘의 일정</div><div class="schedule"><span class="time">AM 10:00</span>${button(state.activity+' · 함께하기','noop','selected','disabled')}<span class="time">PM 07:00</span>${button('둘만의 저녁 대화','noop','','disabled')}</div></div><div class="activities">${[['요리','♧','함께 저녁 준비'],['외출','↗','새 장소의 추억'],['독서','▤','취향을 나누기'],['휴식','☾','피로를 낮추기']].map(([name,icon,desc])=>button(`<span class="activity-icon">${icon}</span>${name}<small>${desc}</small>`,'activity:'+name,state.activity===name?'selected':'')).join('')}</div>${button('이 일정으로 하루 보내기','home-day','primary wide-button')}`:state.phase===1?`<div><div class="eyebrow">DAY 03 / 둘만의 저녁</div><h1>오늘의 선택이<br>대화에 남습니다.</h1></div><div class="panel-box"><p class="diary">${state.activity==='요리'?'함께 만든 저녁이 식탁에 놓였다.<br>그녀가 내가 좋아하는 맛을 묻는다.':state.activity==='외출'?'돌아오는 길, 그녀가 오늘의 장소를 다시 이야기한다.':'조용한 하루가 끝나고 그녀가 먼저 말을 건넨다.'}</p>${meter(state.affinity,'관계 · 편안함')}</div><div class="message-choices">${button('다음에도 너와 함께하고 싶어.','home-promise')}${button('나는 달콤한 맛을 좋아해.','home-promise')}</div>${button('약속을 나누고 다음 날로','home-next','primary wide-button')}`:`<div><div class="eyebrow">DAY 04 / 그녀의 첫 제안</div><h1>어제 나눈 이야기를<br>그녀가 먼저 꺼냅니다.</h1></div><div class="panel-box reveal"><p class="diary">${state.activity==='요리'?'“네가 좋아하는 맛으로 준비했어.<br>오늘도 같이 저녁을 만들자.”':'“어제 함께한 시간이 좋았어.<br>오늘도 너와 보내고 싶어.”'}</p>${meter(state.affinity,'관계 · 친밀함')}</div>${memory('함께한 활동 · '+state.activity+'<br>어제의 약속 · 다음에도 함께하기')}<div class="chips"><span class="chip">추억 +1</span><span class="chip">관계 장면 해금</span></div>${button('둘만의 추억 확인','home-memory','primary wide-button')}`;
 return portrait('g22','유나','성인 안드로이드 · 동거 파트너',next?'어제 네가 말한 걸 기억해. 오늘은 내가 먼저 제안하고 싶어.':'너와 보내는 하루가 조금씩 내 취향이 되는 것 같아.','OUR ROOM / 함께 사는 방')+`<div class="panel">${progress()}${content}<div class="day-dots" aria-label="14일 중 ${next?4:3}일째">${Array.from({length:14},(_,i)=>`<i class="${i<(next?4:3)?'done':''}"></i>`).join('')}</div><div class="status" role="status">${state.notice}</div></div>`;
}
function salon(){
 const closed=state.phase>0;
 let content=!closed?`<div><div class="eyebrow">NIGHT 05 / 영업 중</div><h1>오늘의 주문을<br>누구에게 맡길까요?</h1></div><div class="witches">${[['리엘','g23','조향'],['모르나','g21','연금술'],['루나','g25','응대']].map(([n,g,job])=>button(`<img src="${art(g)}" alt="${n}">${n}<small>${job}</small>`,'witch:'+n,state.witch===n?'selected':'')).join('')}</div><div class="panel-box"><div class="box-title"><span>남은 주문 2건</span><span>특기 일치 보너스</span></div><div class="order"><div>달빛 향수<small>조향 · ${state.witch==='리엘'?'특기 일치 · 수익 +20%':'기본 수익'}</small></div><span class="price">120 G</span></div><div class="order"><div>별빛 물약<small>연금술 · 재료 2개</small></div><span class="price">80 G</span></div></div>${button(state.witch+'에게 배정 · 영업 마치기','salon-close','primary wide-button')}`:`<div><div class="eyebrow">CLOSED / ${state.witch}와 단둘이</div><h1>문을 닫은 뒤,<br>그녀의 다른 이야기가 열립니다.</h1></div><div class="panel-box"><div class="appointment"><div class="seal">☾</div><div>폐점 후 특별 예약<br><small class="muted">오늘 함께 일한 마녀 · ${state.witch}</small></div></div><div style="margin-top:16px">${meter(state.affinity,'관계 · 사적인 신뢰')}</div></div>${memory('오늘의 영업을 함께 마쳤다.<br>그녀가 처음으로 자신의 비밀을 꺼냈다.')}<div class="message-choices">${button('네가 직접 만든 향이 가장 좋았어.','salon-talk')}</div>${button(state.phase===2?'특별 예약 장면 · 앨범 보기':'그녀의 이야기를 더 듣기','salon-talk','primary wide-button')}`;
 return portrait(state.witch==='모르나'?'g21':state.witch==='루나'?'g25':'g23',state.witch,'밤의 마녀 · 비밀 살롱',state.phase===2?'다음 예약은 다른 손님 말고, 너를 위해 비워둘게.':closed?'영업할 때는 말하지 못했지만… 오늘 네가 있어 다행이었어.':'오늘은 바쁘겠네. 내 특기에 맞는 주문을 골라줘.','MIDNIGHT SALON / 비밀 살롱')+`<div class="panel">${progress()}${content}<div class="status" role="status">${state.notice}</div></div>`;
}
function rpg(){
 const victory=state.enemy<=0;
 const world=victory?portrait('g24','에린','엘프 사수 · 원정 동료','아까 나를 보호해준 거, 알고 있었어. 다음 원정도 함께 가고 싶어.','CAMP / 귀환 후 야영지'):`<div class="battlefield"><div class="mountain"></div><img class="ally-art" src="${art('g24')}" alt="원정 동료 일러스트"><div class="enemy"></div><div class="enemy-eye"></div><div class="enemy-hp">유적의 파수꾼${meter(state.enemy,'HP')}</div><span class="world-label">왕도 외곽 · 전투 3 / 3</span><div class="battle-info"><div class="unit">리아 <small>인간 기사</small>${meter(86,'HP')}</div><div class="unit">에린 <small>엘프 사수</small>${meter(72,'HP')}</div></div></div>`;
 let content=victory?`<div class="eyebrow">EXPEDITION COMPLETE</div><div class="result reveal">VICTORY</div><div class="panel-box"><div class="box-title">원정 보상</div><div class="chips"><span class="chip">골드 +120</span><span class="chip">신뢰 +8</span><span class="chip rare">개인 의뢰 해금</span></div></div>${memory('기사의 엄호로 에린을 보호했다.<br>귀환 뒤 그녀가 그 선택을 기억한다.')}<div class="message-choices">${button('네가 무사히 돌아와서 다행이야.','rpg-talk')}</div>${button('에린과 귀환 후 대화','rpg-talk','primary wide-button')}`:`<div><div class="eyebrow">TURN ${state.turn} / 리아의 행동</div><h1>좋아하는 동료와<br>함께 이기는 전투.</h1><p class="muted">공격 · 엄호 · 합동 기술</p></div><div class="commands">${button('검격<small>단일 피해 · 25</small>','attack')}${button('엄호<small>사수 보호 · 신뢰 +3</small>','guard')}${button('엄호 사격<small>합동 기술 · 피해 45</small>','combo','selected')}${button('회복<small>체력 회복 · 다음 턴 준비</small>','heal')}</div><div class="panel-box"><div class="box-title"><span>전투 기록</span><span class="turn">선택이 관계에 남습니다</span></div><div class="combat-log">${state.log}</div></div><div>${meter(state.affinity,'동료 신뢰')}</div>`;
 return world+`<div class="panel">${progress()}${content}<div class="status" role="status">${state.notice}</div></div>`;
}
function fox(){
 const night=state.phase===2;
 let content=`<div><div class="eyebrow">DAY 02 / ${night?'밤의 만남':'낮의 비밀 메시지'}</div><h1>${night?'나에게만 보여주는<br>그녀의 본모습.':'어제의 답장이<br>오늘의 관계를 바꿉니다.'}</h1></div>`;
 if(!night){content+=`<div class="panel-box"><div class="chat-header"><img class="avatar" src="${art('g25')}" alt="시즈쿠"><div>시즈쿠<div class="online">● 지금 접속 중</div></div></div><div class="chat"><div class="bubble">오늘도 정체를 들킬 뻔했어.<br>너에게만 이야기하고 싶었어.<small>12:04</small></div>${state.phase===1?`<div class="bubble mine">${state.message}<small>12:05 · 읽음</small></div><div class="bubble reveal">네가 그렇게 말해줘서 안심했어.<br>오늘 밤, 나를 만나줄래?<small>12:06</small></div>`:''}</div></div>${state.phase===0?`<div class="message-choices">${button('어떤 모습이어도 너는 너야.','fox-reply')}${button('괜찮아. 천천히 말해줘.','fox-reply-soft')}</div>`:button('밤의 만남으로 이어가기','fox-meet','primary wide-button')}`;}
 else{content+=`<div class="panel-box reveal"><p class="diary">“어떤 모습이어도 나라고 했지.<br>그 말을 믿고, 오늘은 숨기지 않을게.”</p>${meter(state.affinity,'관계 · 비밀을 맡긴 사이')}</div>${memory('낮에 전한 답장 · '+state.message+'<br>밤의 만남에서 본모습을 드러냈다.')}<div class="chips"><span class="chip rare">둘만의 비밀 +1</span><span class="chip">만남 이미지 해금</span></div>${button('이 밤을 추억으로 남기기','fox-memory','primary wide-button')}`;}
 return portrait('g25','시즈쿠','성인 여우 요괴 · 비밀연애',night?'나에게 했던 말을 기억해. 그래서 오늘은 보여주고 싶었어.':'낮에는 평범한 모습으로 지내. 내 비밀은 너만 알고 있어.','SECRET / '+(night?'밤의 약속':'낮의 연락'))+`<div class="panel">${progress()}${content}<div class="status" role="status">${state.notice}</div></div>`;
}
function render(){const id=titles[gameId]?gameId:'g21';const views={g21:workshop,g22:home,g23:salon,g24:rpg,g25:fox};const period=id==='g22'?`${state.day} / 14일`:id==='g25'?'2 / 7일':id==='g24'?`원정 03`:'밤 05';root.innerHTML=`<div class="screen ${themes[id]}"><header class="hud"><div class="game-title"><small>${{g21:'INHERITANCE WORKSHOP',g22:'FOURTEEN DAYS WITH YOU',g23:'MIDNIGHT CONFIDENCE',g24:'ROYAL CONTRACT',g25:'SEVEN SECRET NIGHTS'}[id]}</small>${titles[id]}</div><div class="resources"><span>${id==='g21'?'제작 재료':'진행'}<b>${id==='g21'?state.materials:period}</b></span><span>${id==='g23'?'골드':'관계'}<b>${id==='g23'?state.gold+' G':'♥ '+state.affinity}</b></span><span>추억<b>${state.album}</b></span></div></header><div class="body">${views[id]()}</div><footer class="bottom-bar"><span>선택 → 함께한 사건 → 관계와 추억</span>${button('처음부터','reset')}</footer></div>`;}
function act(action){state.notice='';const [key,value]=action.split(':');switch(key){case'reset':state=initial();break;case'collect':state.phase=1;state.materials+=8;state.notice='의뢰 완료 · 제작 재료 +8 · 마족형 원형 획득';break;case'trait':state.trait=value;break;case'combine':if(state.materials<12)return;state.materials-=12;state.phase=2;state.notice='합성 완료 · '+state.trait+' 승계';break;case'workshop-talk':state.message='stars';state.affinity=Math.min(100,state.affinity+8);state.album=3;state.notice='첫 약속을 기억했습니다 · 별을 보는 장면이 앨범에 추가됩니다';break;case'activity':state.activity=value;break;case'home-day':state.phase=1;state.affinity+=5;state.notice='함께한 활동 · '+state.activity;break;case'home-promise':state.message='promise';state.notice='취향과 약속을 관계 기록에 남겼습니다';break;case'home-next':state.phase=2;state.day=4;state.affinity+=8;state.album=3;state.notice='다음 날 · 어제의 대화가 오늘의 제안으로 이어집니다';break;case'home-memory':state.notice='추억 앨범 · 함께 만든 첫 저녁 / 관계 장면 1개 해금';break;case'witch':state.witch=value;break;case'salon-close':state.phase=1;state.gold+=state.witch==='리엘'?224:200;state.affinity+=5;state.notice='영업 완료 · 폐점 후 '+state.witch+'의 개인 이야기';break;case'salon-talk':state.phase=2;state.affinity=Math.min(100,state.affinity+8);state.album=3;state.notice='다음 특별 예약 해금 · 둘만의 만남이 앨범에 남습니다';break;case'attack':state.enemy=Math.max(0,state.enemy-25);state.turn++;state.log='리아의 검격 · 파수꾼에게 25 피해';break;case'guard':state.affinity=Math.min(100,state.affinity+3);state.enemy=Math.max(0,state.enemy-15);state.turn++;state.log='리아가 에린을 엄호했다.<br>에린의 반격 · 15 피해 · 신뢰 +3';break;case'combo':state.enemy=Math.max(0,state.enemy-45);state.turn++;state.log='합동 기술 · 엄호 사격!<br>기사와 사수가 함께 45 피해';break;case'heal':state.turn++;state.log='리아와 에린이 체력을 회복했다.';break;case'rpg-talk':state.phase=2;state.album=3;state.notice='에린의 개인 의뢰 해금 · 야영지의 대화를 추억으로 저장';break;case'fox-reply':case'fox-reply-soft':state.phase=1;state.affinity+=7;state.message=key==='fox-reply'?'어떤 모습이어도 너는 너야.':'괜찮아. 천천히 말해줘.';break;case'fox-meet':state.phase=2;state.affinity+=8;state.album=3;state.notice='낮의 답장이 밤의 만남을 바꿨습니다';break;case'fox-memory':state.notice='추억 앨범 · 본모습을 처음 보여준 밤';break;default:return;}if(gameId==='g24'&&state.enemy<=0){state.phase=Math.max(1,state.phase);state.notice='원정 성공 · 개인 의뢰와 귀환 후 대화 해금';}render();}
root.addEventListener('click',e=>{const target=e.target.closest('button[data-action]');if(target&&!target.disabled)act(target.dataset.action);});
render();
// Keep the proposal's embedded game at its content height on desktop and mobile.
if(window.parent!==window){const notifySize=()=>window.parent.postMessage({type:'game-preview-height',height:Math.ceil(root.getBoundingClientRect().height)},location.origin==='null'?'*':location.origin);new ResizeObserver(notifySize).observe(root);notifySize();}
